### ISSUE TITLE
`Lifts` not included when running `dune runtest`

### ISSUE THREAD

**Issue by lukstafi** [metaocaml/metaocaml-opam#20]
Hi! Maybe `lifts` is not pulled into the `metaocaml` package? For me, `dune build` works, but `dune runtest` fails with:
```
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Lifts referenced from lib/ocannl.cmxa(Ocannl__Shape),
           lib/ocannl.cmxa(Ocannl__Ndarray)
```
(where my project is called `ocannl` and has the modules `Shape`, `Ndarray` in `lib/` using `Lifts`).
I solved this problem by copying `lifts.ml` into my `lib/`.

**Comment by yallop** [comment]
This might be caused by using the `ocaml` rather than the `metaocaml` toolchain:

```
$ metaocaml
BER MetaOCaml toplevel, version N 111
        OCaml version 4.11.1

# Lifts.Lift_int.lift 3;;
- : int code = .<3>. 
# 
$ ocaml
        OCaml version 4.11.1

# Lifts.Lift_int.lift 3;;
Line 1:
Error: Reference to undefined global `Lifts'
```

or by something like a missing `metaocaml` in the `libraries` clause in your `dune`  configuration.

**Comment by lukstafi** [comment]
I'm closing this since it's perhaps a corner case of `dune runtest` and I only need a small function from `Lifts`.
